[package]
name = "passlane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
clipboard = "0.5.0"
clap = { version = "3.0", features = ["derive"] }
csv = "1.1.6"
serde = { version = "1.0.137", features = ["derive"] }
magic-crypt = "3.1.10"
dirs = "4.0.0"
pwhash = "1.0.0"
regex = "1.5.5"
keyring = "1.1.2"
